# Generated by Django 6.0.5 on 2026-05-30 17:21

from django.db import migrations, models

import documents.models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to=documents.models._document_upload_path),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_path",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
