# Generated by Django 6.0.5 on 2026-05-30

import os
from pathlib import Path

from django.db import migrations


def migrate_file_path_to_file_field(apps, schema_editor):
    """Move existing file_path values into the Django FileField."""
    Document = apps.get_model("documents", "Document")
    for doc in Document.objects.all().iterator():
        if doc.file_path and not doc.file:
            path = Path(doc.file_path)
            if path.exists():
                with open(path, "rb") as f:
                    doc.file.save(name=path.name, content=f, save=True)
            else:
                # File no longer on disk — leave file empty but keep file_path for reference
                pass


def reverse_migrate(apps, schema_editor):
    """No-op reverse: file_path is still present."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_add_file_field"),
    ]

    operations = [
        migrations.RunPython(migrate_file_path_to_file_field, reverse_migrate),
    ]